# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: image/png

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/09558b77-ce05-4ef5-9447-a64e33b2aa4d/transcription
Content-Type: application/json

{
  "prompt": "whatsapp audio"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type:  application/json

{
  "videoId": "09558b77-ce05-4ef5-9447-a64e33b2aa4d",
  "temperature": 0.5,
  "prompt": "Gere um resumo sucinto da transcrição do vídeo informado a seguir: '''{transcription}'''"
}